modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="bananacraft"
version="1.0.0"
displayName="bananacraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="48panda"

[[dependencies.bananacraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.bananacraft]]
    modId="tconstruct"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


